# 와인 데이터 분석

In [11]:
import pandas as pd
pd.__version__

'3.0.5'

## [실습1] 데이터 로딩

In [12]:

# 데이터에 인덱스 포함되어 있는경우, 인덱스 컬럼 지정
df = pd.read_csv('./datas/winemag-data_first150k.csv', index_col=0)
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150930 entries, 0 to 150929
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   country      150925 non-null  str
 1   description  150930 non-null  str
 2   designation  105195 non-null  str
 3   points       150930 non-null  int64
 4   price        137235 non-null  float64
 5   province     150925 non-null  str
 6   region_1     125870 non-null  str
 7   region_2     60953 non-null   str
 8   variety      150930 non-null  str
 9   winery       150930 non-null  str
dtypes: float64(1), int64(1), str(8)
memory usage: 11.5 MB

- 주요 컬럼 : country(와인 생산 국가), description(리뷰) points(점수), price(가격), province(지방)

In [14]:
# 리뷰의 디스크립션 컬럼을 desc로 지정
df.rename({'description':'desc'}, axis=1).head(2)

,country,desc,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez

## [실습2] 데이터 슬라이싱

- 디스크립션 컬럼의 첫번째 데이터를, first_description 이라는 변수에 저장하기

In [15]:
# 방법1
first_description = df['description'].loc[0]
first_description

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

In [16]:
# 방법2
df['description'][0]

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

In [17]:
# 방법3
df.loc[0,'description']

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

In [18]:
# 방법4
df.iloc[0,1]

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

- description column의 값들 중, 첫번재부터 10번째 데이터까지를 first_description 변수에 저장한다.

In [19]:
first_description = df['description'].loc[:9]
first_description

0    This tremendous 100% varietal wine hails from ...
1    Ripe aromas of fig, blackberry and cassis are ...
2    Mac Watson honors the memory of a wine once ma...
3    This spent 20 months in 30% new French oak, an...
4    This is the top wine from La Bégude, named aft...
5    Deep, dense and pure from the opening bell, th...
6    Slightly gritty black-fruit aromas include a s...
7    Lush cedary black-fruit aromas are luxe and of...
8    This re-named vineyard was formerly bottled as...
9    The producer sources from two blocks of the vi...
Name: description, dtype: str

In [20]:
first_description = df['description'].iloc[:9+1]
first_description

0    This tremendous 100% varietal wine hails from ...
1    Ripe aromas of fig, blackberry and cassis are ...
2    Mac Watson honors the memory of a wine once ma...
3    This spent 20 months in 30% new French oak, an...
4    This is the top wine from La Bégude, named aft...
5    Deep, dense and pure from the opening bell, th...
6    Slightly gritty black-fruit aromas include a s...
7    Lush cedary black-fruit aromas are luxe and of...
8    This re-named vineyard was formerly bottled as...
9    The producer sources from two blocks of the vi...
Name: description, dtype: str

In [21]:
# df.loc[] : 사람용, df.iloc[] : 컴퓨터용
# df.loc[행, 열]
df.loc[:9, 'description']

0    This tremendous 100% varietal wine hails from ...
1    Ripe aromas of fig, blackberry and cassis are ...
2    Mac Watson honors the memory of a wine once ma...
3    This spent 20 months in 30% new French oak, an...
4    This is the top wine from La Bégude, named aft...
5    Deep, dense and pure from the opening bell, th...
6    Slightly gritty black-fruit aromas include a s...
7    Lush cedary black-fruit aromas are luxe and of...
8    This re-named vineyard was formerly bottled as...
9    The producer sources from two blocks of the vi...
Name: description, dtype: str

- 인덱스가 1,2,3,4,5,8 인 데이터를, sample_reviews 변수에 저장한다.

In [22]:
# sample_reviews = df.iloc[[1,2,3,4,5,8]]
# sample_reviews = df.iloc[[1,2,3,4,5,8], ]
sample_reviews = df.iloc[[1,2,3,4,5,8], :]
sample_reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,Tinta de Toro,Numanthia
8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,Pinot Noir,Bergström

In [23]:
# 인덱스가 0, 1, 10, 100인 데이터에서, 컬럼이 country, province, region_1, region_2인 데이터만 가져오기
df.loc[[0, 1, 10, 100], ['country', 'province', 'region_1', 'region_2']]

    country            province     region_1     region_2
0        US          California  Napa Valley         Napa
1     Spain      Northern Spain         Toro          NaN
10    Italy  Northeastern Italy       Collio          NaN
100      US          California  South Coast  South Coast

## [실습3] 데이터 필터링 
- Italy 에서 만들어진 와인만 가져오기

In [24]:
# nan 값 포함해서 유니크한 값 가져옴
df['country'].unique()

<StringArray>
[                    'US',                  'Spain',                 'France',
                  'Italy',            'New Zealand',               'Bulgaria',
              'Argentina',              'Australia',               'Portugal',
                 'Israel',           'South Africa',                 'Greece',
                  'Chile',                'Morocco',                'Romania',
                'Germany',                 'Canada',                'Moldova',
                'Hungary',                'Austria',                'Croatia',
               'Slovenia',                      nan,                  'India',
                 'Turkey',              'Macedonia',                'Lebanon',
                 'Serbia',                'Uruguay',            'Switzerland',
                'Albania', 'Bosnia and Herzegovina',                 'Brazil',
                 'Cyprus',              'Lithuania',                  'Japan',
                  'China',            'South Korea',                'Ukraine',
                'England',                 'Mexico',                'Georgia',
             'Montenegro',             'Luxembourg',               'Slovakia',
         'Czech Republic',                  'Egypt',                'Tunisia',
              'US-France']
Length: 49, dtype: str

In [25]:
df['country'].unique().size

49

In [26]:
# unique한 값의 갯수, nan은 제외한 갯수 계산
df['country'].nunique()

48

In [27]:
df.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [28]:
df['country']=='Italy'

0         False
1         False
2         False
3         False
4         False
          ...
150925     True
150926    False
150927     True
150928    False
150929     True
Name: country, Length: 150930, dtype: bool

In [29]:
# - Italy 에서 만들어진 와인만 가져오세요
# df.loc[행,열]
df.loc[df['country']=='Italy', :]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga
35,Italy,"Forest floor, tilled soil, mature berry and a ...",Riserva,90,135.0,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Carillon
37,Italy,"Aromas of forest floor, violet, red berry and ...",NaN,90,29.0,Tuscany,Vino Nobile di Montepulciano,NaN,Sangiovese,Avignonesi
38,Italy,"This has a charming nose that boasts rose, vio...",NaN,90,23.0,Tuscany,Chianti Classico,NaN,Sangiovese,Casina di Cornia
...,...,...,...,...,...,...,...,...,...,...
150920,Italy,"Rich and mature aromas of smoke, earth and her...",Brut Riserva,91,19.0,Northeastern Italy,Trento,NaN,Champagne Blend,Letrari
150922,Italy,Made by 30-ish Roberta Borghese high above Man...,Superiore,91,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,Tocai,Ronchi di Manzano
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [30]:
df.loc[df['country']=='Italy', :]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga
35,Italy,"Forest floor, tilled soil, mature berry and a ...",Riserva,90,135.0,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Carillon
37,Italy,"Aromas of forest floor, violet, red berry and ...",NaN,90,29.0,Tuscany,Vino Nobile di Montepulciano,NaN,Sangiovese,Avignonesi
38,Italy,"This has a charming nose that boasts rose, vio...",NaN,90,23.0,Tuscany,Chianti Classico,NaN,Sangiovese,Casina di Cornia
...,...,...,...,...,...,...,...,...,...,...
150920,Italy,"Rich and mature aromas of smoke, earth and her...",Brut Riserva,91,19.0,Northeastern Italy,Trento,NaN,Champagne Blend,Letrari
150922,Italy,Made by 30-ish Roberta Borghese high above Man...,Superiore,91,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,Tocai,Ronchi di Manzano
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

- 리뷰점수가 95점 이상이고, Australia 또는 New Zealand 에서 만들어진 와인 데이터를 가져오세요

In [31]:
(df['points'] >=95)

0          True
1          True
2          True
3          True
4          True
          ...
150925    False
150926    False
150927    False
150928    False
150929    False
Name: points, Length: 150930, dtype: bool

In [32]:
((df['country'] == 'Australia') | (df['country'] == 'New Zealand'))

0         False
1         False
2         False
3         False
4         False
          ...
150925    False
150926    False
150927    False
150928    False
150929    False
Name: country, Length: 150930, dtype: bool

In [33]:
(df['points'] >=95) & ((df['country'] == 'Australia') | (df['country'] == 'New Zealand'))

0         False
1         False
2         False
3         False
4         False
          ...
150925    False
150926    False
150927    False
150928    False
150929    False
Length: 150930, dtype: bool

In [34]:
# 리뷰점수가 95점 이상이고, Australia 또는 New Zealand 에서 만들어진 와인 데이터를 가져오세요
# df.loc[행, 열]
df.loc[(df['points'] >=95) & ((df['country'] == 'Australia') | (df['country'] == 'New Zealand')) , ]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
2148,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Shiraz,Torbreck
2458,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Cabernet-Shiraz,Hickinbotham
3033,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Cabernet Sauvignon,Penfolds
3044,Australia,"From vines planted in 1912, this has been an i...",Mount Edelstone Vineyard,95,200.0,South Australia,Eden Valley,NaN,Shiraz,Henschke
3047,Australia,"This is a throwback to those brash, flavor-exu...",One,95,95.0,South Australia,Langhorne Creek,NaN,Red Blend,Heartland
...,...,...,...,...,...,...,...,...,...,...
122779,Australia,If Standish's Relic is the feminine side of Sh...,The Standish Single Vineyard,96,135.0,South Australia,Barossa Valley,NaN,Shiraz,Standish
127614,Australia,This stellar wine takes a little time in the g...,Hill of Grace,95,625.0,South Australia,Eden Valley,NaN,Shiraz,Henschke
137383,Australia,The 2007 Astralis impresses for its combinatio...,Astralis,95,225.0,South Australia,Clarendon,NaN,Syrah,Clarendon Hills
150562,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,Shiraz,Penfolds
150563,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,Shiraz,Penfolds

In [35]:
df.loc[(df['points'] >=95) & ((df['country'] == 'Australia') | (df['country'] == 'New Zealand')) , ].shape

(82, 10)

- 방법2

In [36]:
(df['points'] >=95) & (df['country'].isin(['Australia', 'New Zealand']))

0         False
1         False
2         False
3         False
4         False
          ...
150925    False
150926    False
150927    False
150928    False
150929    False
Length: 150930, dtype: bool

In [37]:
df.loc[(df['points'] >=95) & (df['country'].isin(['Australia', 'New Zealand'])), ]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
2148,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Shiraz,Torbreck
2458,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Cabernet-Shiraz,Hickinbotham
3033,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Cabernet Sauvignon,Penfolds
3044,Australia,"From vines planted in 1912, this has been an i...",Mount Edelstone Vineyard,95,200.0,South Australia,Eden Valley,NaN,Shiraz,Henschke
3047,Australia,"This is a throwback to those brash, flavor-exu...",One,95,95.0,South Australia,Langhorne Creek,NaN,Red Blend,Heartland
...,...,...,...,...,...,...,...,...,...,...
122779,Australia,If Standish's Relic is the feminine side of Sh...,The Standish Single Vineyard,96,135.0,South Australia,Barossa Valley,NaN,Shiraz,Standish
127614,Australia,This stellar wine takes a little time in the g...,Hill of Grace,95,625.0,South Australia,Eden Valley,NaN,Shiraz,Henschke
137383,Australia,The 2007 Astralis impresses for its combinatio...,Astralis,95,225.0,South Australia,Clarendon,NaN,Syrah,Clarendon Hills
150562,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,Shiraz,Penfolds
150563,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,Shiraz,Penfolds