#  와인데이터 분석2

- datas/winemag-data.csv

In [1]:
import pandas as pd
pd.__version__

'3.0.5'

In [2]:
# 로컬에서 로딩

data = "./datas/winemag-data.csv"
# 첫번째 컬럼을 index에 사용
df = pd.read_csv(data, index_col = 0 )
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [3]:
# 1. title 컬럼에 데이터가 비어있는것이 있는지 확인한다.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  str
 1   description            129971 non-null  str
 2   designation            92506 non-null   str
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  str
 6   region_1               108724 non-null  str
 7   region_2               50511 non-null   str
 8   taster_name            103727 non-null  str
 9   taster_twitter_handle  98758 non-null   str
 10  title                  129971 non-null  str
 11  variety                129970 non-null  str
 12  winery                 129971 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 12.9 MB

In [4]:
df.notna().sum()

country                  129908
description              129971
designation               92506
points                   129971
price                    120975
province                 129908
region_1                 108724
region_2                  50511
taster_name              103727
taster_twitter_handle     98758
title                    129971
variety                  129970
winery                   129971
dtype: int64

In [5]:
df['title'].unique()

<StringArray>
[                                                                    'Nicosia 2013 Vulkà Bianco  (Etna)',
                                                         'Quinta dos Avidagos 2011 Avidagos Red (Douro)',
                                                         'Rainstorm 2013 Pinot Gris (Willamette Valley)',
                                   'St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)',
                   'Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)',
                                                 'Tandem 2011 Ars In Vitro Tempranillo-Merlot (Navarra)',
                                                      'Terre di Giurfo 2013 Belsito Frappato (Vittoria)',
                                                                 'Trimbach 2012 Gewurztraminer (Alsace)',
                                                   'Heinz Eifel 2013 Shine Gewürztraminer (Rheinhessen)',
                                               'Jean-Baptiste Adam 2012 Les Natures Pinot Gris (Alsace)',
 ...
                                                                           'COS 2013 Frappato (Sicilia)',
                                        'Cusumano 2012 Sàgana Tenuta San Giacomo Nero d'Avola (Sicilia)',
                                                     'Dalton 2012 Oak Aged Cabernet Sauvignon (Galilee)',
                             'Domaine Ehrhart 2013 Domaine Saint-Rémy Herrenweg Gewurztraminer (Alsace)',
                          'Domaine Rieflé-Landmann 2013 Seppi Landmann Vallée Noble Pinot Gris (Alsace)',
 'Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)',
                                                                     'Citation 2004 Pinot Noir (Oregon)',
                                                    'Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)',
                                                         'Domaine Marcel Deiss 2012 Pinot Gris (Alsace)',
                           'Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)']
Length: 118840, dtype: str

In [6]:
df['title'].nunique()

118840

In [7]:
# 2. 인덱스를 title 컬름으로 변경
df.set_index('title').info()

<class 'pandas.DataFrame'>
Index: 129971 entries, Nicosia 2013 Vulkà Bianco  (Etna) to Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  str
 1   description            129971 non-null  str
 2   designation            92506 non-null   str
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  str
 6   region_1               108724 non-null  str
 7   region_2               50511 non-null   str
 8   taster_name            103727 non-null  str
 9   taster_twitter_handle  98758 non-null   str
 10  variety                129970 non-null  str
 11  winery                 129971 non-null  str
dtypes: float64(1), int64(1), str(10)
memory usage: 12.9+ MB

In [8]:
df = df.set_index('title')
df

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel),Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
Citation 2004 Pinot Noir (Oregon),US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Pinot Noir,Citation
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace),France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Gresser
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace),France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

## 문제1

In [9]:
# 먼저 데이터가 비어있는것이 있는지 확인한다.
# 가격이 있는 데이터만  가져온다
# 새로운 컬럼 critic 만들고, everyone 이라고 값 넣는다
# 포인트 컬럼은 수치로 되어있다. 이 컬럼의 기초통계데이터를 확인하시오. (평균, 최대 최소 등)
# taster_name 컬럼은 사람 이름으로 되어있다. 몇명의 사람들이 평가를 한것인까?
# 포인트의 평균을 구하시오
# 테이스터들의 이름을 전부 확인하시오

In [10]:
# 먼저 데이터가 비어있는것이 있는지 확인한다.
df.info()

<class 'pandas.DataFrame'>
Index: 129971 entries, Nicosia 2013 Vulkà Bianco  (Etna) to Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  str
 1   description            129971 non-null  str
 2   designation            92506 non-null   str
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  str
 6   region_1               108724 non-null  str
 7   region_2               50511 non-null   str
 8   taster_name            103727 non-null  str
 9   taster_twitter_handle  98758 non-null   str
 10  variety                129970 non-null  str
 11  winery                 129971 non-null  str
dtypes: float64(1), int64(1), str(10)
memory usage: 12.9+ MB

In [11]:
df.isna().sum()

country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
variety                      1
winery                       0
dtype: int64

In [12]:
# nan의 갯수의 합
df.isna().sum().sum()

np.int64(204752)

- 가격이 있는 데이터만  가져온다

In [13]:
df['price'].notna()

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                        False
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                             True
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                             True
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                       True
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                       True
                                                                                                         ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)     True
Citation 2004 Pinot Noir (Oregon)                                                                         True
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                        True
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                             True
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                               True
Name: price, Length: 129971, dtype: bool

In [14]:
# 가격이 있는 데이터만  가져온다
df.loc[df['price'].notna(), ]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks
Tandem 2011 Ars In Vitro Tempranillo-Merlot (Navarra),Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tempranillo-Merlot,Tandem
...,...,...,...,...,...,...,...,...,...,...,...,...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel),Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
Citation 2004 Pinot Noir (Oregon),US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Pinot Noir,Citation
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace),France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Gresser
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace),France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

In [15]:
# 가격이 있는 데이터의 갯수
df.loc[df['price'].notna(), ].shape

(120975, 12)

In [16]:
# 새로운 컬럼 critic 만들고, everyone 이라고 값 넣는다
df['critic'] = 'everyone'
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic
title,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm,everyone
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian,everyone
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks,everyone

In [17]:
# 포인트 컬럼은 수치로 되어있다. 이 컬럼의 기초통계데이터를 확인하시오. (평균, 최대 최소 등)
df['points'].mean()

np.float64(88.44713820775404)

In [18]:
df['points'].max()

np.int64(100)

In [19]:
df['points'].min()

np.int64(80)

In [20]:
# nan 이 한개 있음
df['taster_name'].unique()

<StringArray>
[     'Kerin O’Keefe',         'Roger Voss',       'Paul Gregutt',
 'Alexander Peartree',  'Michael Schachner', 'Anna Lee C. Iijima',
     'Virginie Boone',      'Matt Kettmann',                  nan,
   'Sean P. Sullivan',         'Jim Gordon',     'Joe Czerwinski',
   'Anne Krebiehl MW',      'Lauren Buzzeo',      'Mike DeSimone',
       'Jeff Jenssen',    'Susan Kostrzewa',       'Carrie Dykes',
        'Fiona Adams',  'Christina Pickard']
Length: 20, dtype: str

In [21]:
# taster_name 컬럼은 사람 이름으로 되어있다. 몇명의 사람들이 평가를 한것인까?
df['taster_name'].unique().__len__()

20

In [22]:
df['taster_name'].nunique()

19

In [23]:
# 포인트의 평균을 구하시오
df['points'].mean()

np.float64(88.44713820775404)

In [24]:
df['points'].describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [25]:
# taster_name 컬럼은 사람 이름으로 되어있다. 몇명의 사람들이 평가를 한것인까?
# 테이스터들의 이름을 전부 확인하시오

In [26]:
df['taster_name']

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                             Kerin O’Keefe
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                                    Roger Voss
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                                  Paul Gregutt
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                      Alexander Peartree
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                            Paul Gregutt
                                                                                                                ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)    Anna Lee C. Iijima
Citation 2004 Pinot Noir (Oregon)                                                                              Paul Gregutt
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                               Roger Voss
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                                    Roger Voss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                                      Roger Voss
Name: taster_name, Length: 129971, dtype: str

In [27]:
# 테이스터들의 이름을 전부 확인하시오, nan  이 포함 되어 있음
unique_test = df['taster_name'].unique()
print(unique_test)
len(unique_test)

<StringArray>
[     'Kerin O’Keefe',         'Roger Voss',       'Paul Gregutt',
 'Alexander Peartree',  'Michael Schachner', 'Anna Lee C. Iijima',
     'Virginie Boone',      'Matt Kettmann',                  nan,
   'Sean P. Sullivan',         'Jim Gordon',     'Joe Czerwinski',
   'Anne Krebiehl MW',      'Lauren Buzzeo',      'Mike DeSimone',
       'Jeff Jenssen',    'Susan Kostrzewa',       'Carrie Dykes',
        'Fiona Adams',  'Christina Pickard']
Length: 20, dtype: str

20

In [28]:
# 테이스터들의 이름을 전부 확인하시오
unique_test = unique_test[pd.notna(unique_test)]
print(unique_test)
print(len(unique_test))

<StringArray>
[     'Kerin O’Keefe',         'Roger Voss',       'Paul Gregutt',
 'Alexander Peartree',  'Michael Schachner', 'Anna Lee C. Iijima',
     'Virginie Boone',      'Matt Kettmann',   'Sean P. Sullivan',
         'Jim Gordon',     'Joe Czerwinski',   'Anne Krebiehl MW',
      'Lauren Buzzeo',      'Mike DeSimone',       'Jeff Jenssen',
    'Susan Kostrzewa',       'Carrie Dykes',        'Fiona Adams',
  'Christina Pickard']
Length: 19, dtype: str
19

##  문제2

In [29]:
# 각 테이스터들은, 각각 몇개의 와인을 테스트 했는지 확인하시오. ( 테스터 이름, 갯수 )
# 포인트의 평균을 구하고, 리뷰의 포인트값이, 평균보다 큰 데이터 (즉, 평가가 좋은 와인) 만 가져오시오.
# points 컬럼의 median 값은?
# 각 국가별로는 몇개의 리뷰가 있는지, 각국가별 리뷰수를 구하시오.
# 나는 경제적이므로, 가격대비 포인트가 가장 큰 와인을 사려한다. 해당 와인의 title은?

In [30]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic
title,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone

In [31]:
df['taster_name'].head(5)

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                           Kerin O’Keefe
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                  Roger Voss
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                Paul Gregutt
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                    Alexander Peartree
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)          Paul Gregutt
Name: taster_name, dtype: str

In [32]:
# 각 테이스터들은, 각각 몇개의 와인을 테스트 했는지 확인하시오. ( 테스터 이름, 갯수 )
df['taster_name'].value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

In [33]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic
title,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone

In [34]:
# 포인트의 평균을 구하고, 리뷰의 포인트값이, 평균보다 큰 데이터 (즉, 평가가 좋은 와인) 만 가져오시오.
df['points'].mean()

np.float64(88.44713820775404)

In [35]:
df['points'] > df['points'].mean()

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                        False
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                            False
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                            False
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                      False
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                      False
                                                                                                         ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)     True
Citation 2004 Pinot Noir (Oregon)                                                                         True
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                        True
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                             True
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                               True
Name: points, Length: 129971, dtype: bool

In [36]:
# 리뷰의 포인트값이, 평균보다 큰 데이터 
df.loc[df['points'] > df['points'].mean(), :]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic
title,,,,,,,,,,,,,
Dopff & Irion 2004 Schoenenbourg Grand Cru Vendanges Tardives Riesling (Alsace),France,Medium-gold in color. Complex and inviting nos...,Schoenenbourg Grand Cru Vendanges Tardives,92,80.0,Alsace,Alsace,NaN,NaN,NaN,Riesling,Dopff & Irion,everyone
Ceretto 2003 Bricco Rocche Prapó (Barolo),Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Nebbiolo,Ceretto,everyone
Matrix 2007 Stuhlmuller Vineyard Chardonnay (Alexander Valley),US,The vineyard is one of the better Chardonnay s...,Stuhlmuller Vineyard,92,36.0,California,Alexander Valley,Sonoma,NaN,NaN,Chardonnay,Matrix,everyone
Mauritson 2007 Rockpile Cemetary Vineyard Zinfandel (Rockpile),US,Defines Rockpile Zinfandel in intensity of fru...,Rockpile Cemetary Vineyard,92,39.0,California,Rockpile,Sonoma,NaN,NaN,Zinfandel,Mauritson,everyone
Henry's Drive Vignerons 2006 Parson's Flat Shiraz-Cabernet Sauvignon (Padthaway),Australia,The blend is roughly two-thirds Shiraz and one...,Parson's Flat,92,40.0,South Australia,Padthaway,NaN,Joe Czerwinski,@JoeCz,Shiraz-Cabernet Sauvignon,Henry's Drive Vignerons,everyone
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel),Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),everyone
Citation 2004 Pinot Noir (Oregon),US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Pinot Noir,Citation,everyone
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace),France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Gresser,everyone
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss,everyone
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace),France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit,everyone

In [37]:
# points 컬럼의 median 값은?
df['points'].median()

np.float64(88.0)

In [38]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic
title,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone

In [39]:
# 각 국가별로는 몇개의 리뷰가 있는지, 각국가별 리뷰수를 구하시오.
pd.DataFrame(df.groupby('country')['description'].count())

                        description
country
Argentina                      3800
Armenia                           2
Australia                      2329
Austria                        3345
Bosnia and Herzegovina            2
Brazil                           52
Bulgaria                        141
Canada                          257
Chile                          4472
China                             1
Croatia                          73
Cyprus                           11
Czech Republic                   12
Egypt                             1
England                          74
France                        22093
Georgia                          86
Germany                        2165
Greece                          466
Hungary                         146
India                             9
Israel                          505
Italy                         19540
Lebanon                          35
Luxembourg                        6
Macedonia                        12
Mexico                           70
Moldova                          59
Morocco                          28
New Zealand                    1419
Peru                             16
Portugal                       5691
Romania                         120
Serbia                           12
Slovakia                          1
Slovenia                         87
South Africa                   1401
Spain                          6645
Switzerland                       7
Turkey                           90
US                            54504
Ukraine                          14
Uruguay                         109

In [40]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic
title,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone

In [41]:
# 나는 경제적이므로, 가격대비 포인트가 가장 큰 와인을 사려한다. 해당 와인의 title은?
# 가성비 높은 와인 찾기

df['price']

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                         NaN
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                            15.0
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                            14.0
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                      13.0
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                      65.0
                                                                                                         ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)    28.0
Citation 2004 Pinot Noir (Oregon)                                                                        75.0
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                       30.0
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                            32.0
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                              21.0
Name: price, Length: 129971, dtype: float64

In [42]:
# 가격대비 포인트가 가장 큰 와인을 사려한다.
# 가성비 : 포인트 / 가격
df['cost-effect'] = (df['points'] / df['price'])

In [43]:
df['cost-effect'].max()

np.float64(21.5)

In [44]:
df.loc[df['cost-effect'] == df['cost-effect'].max(), :]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic,cost-effect
title,,,,,,,,,,,,,,
Bandit NV Merlot (California),US,"There's a lot going on in this Merlot, which i...",NaN,86,4.0,California,California,California Other,NaN,NaN,Merlot,Bandit,everyone,21.5
Cramele Recas 2011 UnWineD Pinot Grigio (Viile Timisului),Romania,Notes of sun-dried hay and green flower highli...,UnWineD,86,4.0,Viile Timisului,NaN,NaN,Anna Lee C. Iijima,NaN,Pinot Grigio,Cramele Recas,everyone,21.5

In [45]:
# 가성비가 가장 높은 와인 타이틀
list(df.loc[df['cost-effect'] == df['cost-effect'].max(), :].index)

['Bandit NV Merlot (California)',
 'Cramele Recas 2011 UnWineD Pinot Grigio (Viile Timisului)']

In [46]:
# 가성비 가장 높은 와인의 title, 나라, 가격까지 가져오기
df.loc[df['cost-effect'] == df['cost-effect'].max(), ['country', 'price']]

                                                    country  price
title
Bandit NV Merlot (California)                            US    4.0
Cramele Recas 2011 UnWineD Pinot Grigio (Viile ...  Romania    4.0

- 문제 하나를 해결하기 위해서는 하나의 방법으로 풀수 있는게 아니다. 배운것이 쌓여야만, 큰 문제를 해결할 수 있다.
- 작은 문제를 많이 풀어야 큰 문제를 풀 수 있다.

##  문제3

In [47]:
# 각 테이스터들은, 각각 몇개의 와인을 테스트 했는지 확인하시오. ( 테스터 이름, 갯수 )

In [48]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic,cost-effect
title,,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone,NaN
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone,5.8

In [49]:
# 각 테이스터들은, 각각 몇개의 와인을 테스트 했는지 확인하시오. ( 테스터 이름, 갯수 )
df.groupby('taster_name')[ 'winery'].count()

taster_name
Alexander Peartree      415
Anna Lee C. Iijima     4415
Anne Krebiehl MW       3685
Carrie Dykes            139
Christina Pickard         6
Fiona Adams              27
Jeff Jenssen            491
Jim Gordon             4177
Joe Czerwinski         5147
Kerin O’Keefe         10776
Lauren Buzzeo          1835
Matt Kettmann          6332
Michael Schachner     15134
Mike DeSimone           514
Paul Gregutt           9532
Roger Voss            25514
Sean P. Sullivan       4966
Susan Kostrzewa        1085
Virginie Boone         9537
Name: winery, dtype: int64

In [50]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic,cost-effect
title,,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone,NaN
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone,5.8

## 문제4

In [51]:
# 사람들이 어떤와인을 더 많이 거론했는지 보려한다. 
# "tropical" 이 들어있는 리뷰의 갯수는? "fruity" 라고 들어있는 리뷰의 갯수는?

In [52]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic,cost-effect
title,,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone,NaN
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone,5.8

In [53]:
# 활용 : 최근에 가장 많이 나오는 단어들

In [54]:
# 사람들이 어떤와인을 더 많이 거론했는지 보려한다. 
wine_by_taster = df.groupby(['title'])['taster_name'].nunique().sort_values(ascending=False)
wine_by_taster

title
Pierre Sparr NV Brut Réserve Sparkling (Crémant d'Alsace)                3
Torbreck 2006 The Struie Shiraz (Barossa)                                2
Domaine Charles Baur NV Brut Sparkling (Crémant d'Alsace)                2
Breathless NV Blanc de Noirs Sparkling (Sonoma County)                   2
Doyenne 2011 Grand Ciel Vineyard Syrah (Red Mountain)                    2
                                                                        ..
Rutherford Ranch 2005 Estate Vineyard Cabernet Sauvignon (Rutherford)    0
Rutherford Ranch 2005 Cabernet Sauvignon (Napa Valley)                   0
10Span 2012 Pinot Gris (Monterey County)                                 0
10Span 2012 Chardonnay (Santa Barbara County)                            0
10Span 2011 Pinot Noir (Santa Barbara County)                            0
Name: taster_name, Length: 118840, dtype: int64

In [55]:
# 사람들이 특성의 와인을 거론했는지 보기
# "tropical" 이 들어있는 리뷰의 갯수는?  '열대의'

In [56]:
df['description']

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                        Aromas include tropical fruit, broom, brimston...
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                            This is ripe and fruity, a wine that is smooth...
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                            Tart and snappy, the flavors of lime flesh and...
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                      Pineapple rind, lemon pith and orange blossom ...
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                      Much like the regular bottling from 2012, this...
                                                                                                                               ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)    Notes of honeysuckle and cantaloupe sweeten th...
Citation 2004 Pinot Noir (Oregon)                                                                        Citation is given as much as a decade of bottl...
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                       Well-drained gravel soil gives this wine its c...
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                            A dry style of Pinot Gris, this is crisp with ...
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                              Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: str

In [57]:
df['description'].str.lower()

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                        aromas include tropical fruit, broom, brimston...
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                            this is ripe and fruity, a wine that is smooth...
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                            tart and snappy, the flavors of lime flesh and...
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                      pineapple rind, lemon pith and orange blossom ...
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                      much like the regular bottling from 2012, this...
                                                                                                                               ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)    notes of honeysuckle and cantaloupe sweeten th...
Citation 2004 Pinot Noir (Oregon)                                                                        citation is given as much as a decade of bottl...
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                       well-drained gravel soil gives this wine its c...
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                            a dry style of pinot gris, this is crisp with ...
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                              big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: str

In [58]:
df['description'].str.lower().str.contains("tropical", na=False)

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                         True
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                            False
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                            False
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                      False
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                      False
                                                                                                         ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)    False
Citation 2004 Pinot Noir (Oregon)                                                                        False
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                       False
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                            False
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                              False
Name: description, Length: 129971, dtype: bool

In [59]:

df['description'].str.lower().str.contains("tropical", na=False).sum()

np.int64(3800)

In [60]:
# "fruity" 라고 들어있는 리뷰의 갯수는?  '과일 같은, 과일 향이 나는'

In [61]:
df['description'].str.lower()

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                        aromas include tropical fruit, broom, brimston...
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                            this is ripe and fruity, a wine that is smooth...
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                            tart and snappy, the flavors of lime flesh and...
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                      pineapple rind, lemon pith and orange blossom ...
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                      much like the regular bottling from 2012, this...
                                                                                                                               ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)    notes of honeysuckle and cantaloupe sweeten th...
Citation 2004 Pinot Noir (Oregon)                                                                        citation is given as much as a decade of bottl...
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                       well-drained gravel soil gives this wine its c...
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                            a dry style of pinot gris, this is crisp with ...
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                              big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: str

In [62]:
df['description'].str.lower().str.contains("fruity", na=False).sum()

np.int64(9455)

In [63]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic,cost-effect
title,,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone,NaN
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone,5.8

## 문제5

In [64]:
# 별점 시스템을 만들려고 한다. 따라서 별점에 대한 데이터가 필요하다. 
# 별점은 1,2,3 즉 3개로 만들것이다. 포인트가 95점 이상이면 3점, 85점 이상이면 2점, 나머지는 1점으로 할 것이다. 
# 리뷰데이터를 통해 각 데이터의 별점을 구하시오.

In [65]:
# 함수 정의 문제 해결하기
def get_stars(point):

In [66]:
get_stars(90)

'**'

In [67]:
df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic,cost-effect
title,,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone,NaN
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone,5.8

In [68]:
# points 컬럼의 점수에 따른 start_point 컬럼 생성하기
df['start_point'] = 
df.head(3)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery,critic,cost-effect,start_point
title,,,,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia,everyone,NaN,**
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos,everyone,5.800000,**
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm,everyone,6.214286,**